#! /bin/sh

name=mlibc
version=8beff77484af4c8bddd1febd922f3d31ede9be40
revision=1
git_url="https://github.com/cpplover0/orange-mlibc.git"
commit=${version}
imagedeps="build-essential meson ninja-build"
hostdeps="gcc pkg-config libgcc-binaries"
builddeps="freestnd-c-hdrs freestnd-cxx-hdrs frigg"
deps="linux-headers mlibc-headers"

configure() {
    CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS -Wl,/usr/local/libgcc-binaries/libgcc-x86_64.a" \
    meson_configure_noflags_no_cross \
        --cross-file "${base_dir}/build-support/cross-file-x86_64-linux.txt" \
        --buildtype=release \
        -Dno_headers=true \
        -Ddefault_library=both \
        -Dlinux_kernel_headers=${sysroot_dir}${prefix}/include \
        -Dlibgcc_dependency=false \
        -Duse_freestnd_hdrs=enabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}