# Timeout in seconds that Limine will use before automatically booting.
timeout: 0
term_foreground: EEEEEEEE
# term_background: 000011
wallpaper: boot():/boot/bg.jpg

/Orange
    protocol: limine
    path: boot():/boot/kernel
    module_path: boot():/boot/initrd.ustar
    cmdline: init=/bin/bash

