#!/bin/sh

export LD_LIBRARY_PATH="${host_dest_dir}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:/usr/lib/x86_64-linux-gnu/"

[ -z "$VALADIR" ] && ( echo "Please set VALADIR environment variable"; exit 1 )
valac --vapidir="$VALADIR" "$@"