#!/bin/bash

unset LD_LIBRARY_PATH

_path="$1"
shift 1

_temp=$(mktemp)
cp -p "${_path}" "${_temp}"
 execstack -c "${_temp}"
patchelf --set-interpreter "${RUN_WRAPPER_INTERP}" "${_temp}"
export LD_LIBRARY_PATH="${RUN_WRAPPER_LD_LIBRARY_PATH}"
_path="${_temp}"

"${_path}" "$@"