
Section "Device"
    Identifier  "DRM Graphics"
    Driver      "modesetting"
EndSection

Section "InputDevice"
Identifier "Keyboard"
Driver "kbd"
Option "Device" "/dev/keyboard"
Option "Protocol" "Standard"
EndSection