
set(CMAKE_SYSTEM_NAME Orange)
set(CMAKE_SYSTEM_PROCESSOR x86_64) 

set(CMAKE_C_COMPILER x86_64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++)
set(CMAKE_LINKER x86_64-linux-gnu-ld)

set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_C_EXTENSIONS ON)